name: Check code quality

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  format:
    name: Check formatting with clang-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check formatting of all source files
        run: clang-format -i src/*.h src/*.c

      - name: Check for uncommitted changes (fail if there are any)
        run: |
          git diff --exit-code
          git diff --cached --exit-code
